spring.application.name=demo
#in a more serious application, do not store secrets in plain text in this file
#pass them in using environment variables or a secrets manager

#okta.oauth2.issuer=https://{yourOktaDomain}/oauth2/default

#my admin url is https://trial-8520257-admin.okta.com/
okta.oauth2.issuer=https://trial-8520257.okta.com/oauth2/default
okta.oauth2.client-id=0oaxhh4xweQGR7vbX697
okta.oauth2.client-secret=6Nx3QHJduCP1JQZ__SScVZRtkRsabuC8JcvAK0xbDbOkpcstdrJOsB7ymXFdqhLq

okta.oauth2.scopes=openid, profile, email, offline_access, foo, bar

server.port=8080
spring.web.resources.static-locations=classpath:/browser/,classpath:/static/

logging.level.org.springframework.security.web.csrf=TRACE


springdoc.swagger-ui.tagsSorter=alpha
application-description=@project.description@

application-version=@project.version@

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=true
springdoc.use-fqn=true
springdoc.paths-to-exclude=/apilogout

#springdoc.swagger-ui.csrf.enabled=true
#springdoc.swagger-ui.csrf.header-name=X-XSRF-TOKEN

